// Copyright (c) 2026 Andrew Mauer. All Rights Reserved.
// Proprietary and confidential. Unauthorized use prohibited.

/**
 * Domain types for Social Vinyl Mobile
 */

/**
 * Result Pattern (Critical for Phase 1)
 */
export type Result<T, E = Error> =
    | { success: true; data: T }
    | { success: false; error: E };

export type AsyncResult<T, E = Error> = Promise<Result<T, E>>;

export interface WebSocketCallbacks {
    onConnectionStateChange(state: ConnectionState): void;
    onMessage(message: WebSocketMessage): void;
    onError(error: Error): void;
    // Semantic Callbacks for architectural cleanup
    onSessionJoined?(data: { sessionId: string; authToken?: string; username?: string }): void;
    onNowPlaying?(data: NowPlaying): void;
    onSessionEnded?(): void;
    onAccessLevel?(level: string): void;
    // Issue #126
    onBinState?(items: BinItem[]): void;
}

export interface SyncCallbacks {
    onProgress(progress: number): void;
    onStatusChange(status: SyncStatus): void;
}

export interface Release {
    id: number;
    releaseId?: number; // Backend alias
    instanceId?: number; // UNIQUE identifier from Discogs (or instance PK from backend)
    userId: string; // SCOPING: User ID for isolation
    title: string;
    artist: string;
    thumb_url: string | null;
    coverImage?: string; // Backend payload
    added_at: number;
    year?: string;
    genres?: string;
    label?: string;
    format?: string;
    tracks?: string; // JSON String
    isSaved?: boolean;
    isNotable?: boolean;
    spinCount?: number;
    playedAt?: number; // History timestamp (ms)
    totalDuration?: number; // Total duration in seconds (Added for Progress Ring)
}

/**
 * NowPlaying Interface
 * Aligned with specification in Issue #23.
 */
export interface NowPlaying {
    track: string;
    artist: string;
    album: string;
    albumArt?: string;
    timestamp?: number;
    releaseId?: string; // Added for internal linking
    duration?: number;   // Total duration in ms
    position?: number;   // Current playback position in ms
    userHasLiked?: boolean; // If current user has liked this track
    playedBy?: string;   // Attribution - who added this to the bin
    likeCount?: number;  // Total thumbs up for this track
    playedAt?: number;   // Timestamp when playback started (ms)
}

export interface BinItem extends Release {
    /**
     * Identity lifecycle: `item.id` is the Discogs releaseId BEFORE `confirmAdd`,
     * and becomes `instanceId` (backend DB row PK) AFTER `confirmAdd` or `bin-state` sync.
     * Always use `item.id` as the store lookup key. Use `item.releaseId` for Discogs API calls.
     * See: ListeningBinSyncService.removeAlbum JSDoc.
     */
    addedTimestamp: number;
    // Issue #126: Sync status for optimistic updates
    status?: 'synced' | 'pending' | 'error';
    // Issue #126: Helper to track temporary ID for optimistic adds
    tempId?: string;
    // Issue #126: Unique ID generated by frontend to handle duplicate album entries
    frontendId?: string;
    // Backend sends 'requestedBy' instead of 'userId' for server-synced items
    requestedBy?: string;
    // Backend-assigned UUID used for ownership verification on remove
    clientUUID?: string;
}

export type SyncStatus = 'idle' | 'syncing' | 'complete' | 'error';

export type ConnectionState = 'disconnected' | 'connecting' | 'connected' | 'reconnecting';

export interface Track {
    position: string;
    title: string;
    duration: string;
}

export interface BackendAlbum {
    id: number;
    title: string;
    artist: string;
    year?: number;
    thumb?: string;
    genre?: string;
    styles?: string[];
    format?: string;
    country?: string;
    label?: string;
    catno?: string;
    tracks?: Track[];
    isNotable?: boolean;
    isSaved?: boolean;
    addedTimestamp?: number;
    spinCount?: number;
}

/**
 * Session Management Types (Issue #128)
 */
export type SessionRole = 'host' | 'guest' | 'voyeur' | null;

export interface SessionCard {
    id: number;
    name: string;
    code: string;        // 5-char alphanumeric
    active: boolean;
    permanent: boolean;
    isBroadcast: boolean;
    createdAt: string;   // ISO date string
}

export interface SessionHistory {
    id: string; // Internal SQLite ID or Session ID from backend if available
    session_name: string;
    host_username: string;
    started_at: number;
    ended_at: number | null;
    mode: 'party' | 'live' | 'solo';
    guest_count: number;
}

export interface SessionPlay {
    id: string;
    session_id: string;
    release_id: number;
    release_title: string;
    artist: string;
    album_art_url: string | null;
    played_at: number;
    picked_by_username: string | null;
}

export interface WantListItem {
    id: string;
    releaseId: number;
    releaseTitle: string;
    artist: string;
    albumArtUrl: string | null;
    hostUsername: string | null;
    sessionName: string | null;
    sessionId: string | null;
    addedAt: number; // unix ms timestamp
}

export interface SessionCreatedMessage {
    type: 'session-created';
    sessionId: number;
    joinCode: string;
    sessionSecret: string;
    name: string;
    publicUrl: string;
}

export interface SessionJoinedMessage {
    type: 'session-joined';
    sessionId: number;
    name: string;
    joinCode: string;
    sessionSecret: string;
    publicUrl: string;
    hostUsername: string;
    isPermanent: boolean;
    startedAt?: number;
}

export interface SessionLeftMessage {
    type: 'session-left';
}

export interface SessionListMessage {
    type: 'session-list';
    sessions: SessionCard[];
}

export interface LoginResult {
    sessionId?: string;
    token: string;
    userId?: string;
    sessionSecret?: string;
    sessionName?: string;
    joinCode?: string;
    hostUsername?: string;
    isPermanent?: boolean;
}

export interface SyncResult {
    itemCount: number;
    syncTime: number;
    avatarUrl?: string;
}

export interface ScanResponse {
    success: boolean;
    albums?: BackendAlbum[];
    error?: string;
}

export interface SyncState {
    status: SyncStatus;
    progress: number;
    lastSyncTime: number | null;
    error?: string;
}

/**
 * WebSocket Protocol Types
 */

export type WebSocketMessageType =
    | 'WELCOME' | 'welcome'
    | 'ACCESS_LEVEL' | 'access-level'
    | 'SESSION_JOINED' | 'session-joined'
    | 'NOW_PLAYING' | 'now-playing'
    | 'now-playing-cleared'
    | 'SESSION_ENDED' | 'session-ended'
    | 'ERROR' | 'error'
    | 'admin-login-success'
    // New types for Issue #125
    | 'PROTOCOL_HANDSHAKE'
    | 'PROTOCOL_ACK'
    | 'CLIENT_ACTION'
    | 'ACTION_ACK'
    // Session Management (Issue #128)
    | 'session-created'
    | 'session-left'
    | 'session-list'
    // Issue #126
    | 'BIN_STATE' | 'bin-state'
    | 'STATE' | 'state';

export interface WebSocketMessage {
    type?: WebSocketMessageType;
    messageType?: WebSocketMessageType;
    payload?: LoginResult | SyncResult | NowPlaying | { message: string } | Record<string, unknown>;
    sessionId?: string;
    authToken?: string;
    sessionSecret?: string;
    joinCode?: string;
    name?: string;
    publicUrl?: string;
    hostUsername?: string;
    isPermanent?: boolean;
    sessions?: SessionCard[];
    username?: string;
    startedAt?: number;
    // Issue #125: Add actionId and status for ACK correlation
    actionId?: string;
    status?: 'success' | 'error';
    album?: {
        title: string;
        artist: string;
        releaseId: number;
        instanceId?: number;
        coverImage: string;
        tracks?: Track[];
    };
    // Issue #126: Bin State Payload
    bin?: BinItem[];
    message?: string;
}

export interface ProtocolHandshakeMessage {
    type: 'PROTOCOL_HANDSHAKE';
    version: string;
    capabilities: string[];
}

export interface ProtocolAckMessage {
    type: 'PROTOCOL_ACK';
    supported: boolean;
    enabledFeatures: string[];
}

export interface ClientActionMessage {
    type: 'CLIENT_ACTION';
    action: string;
    actionId: string;
    payload: any;
}

export interface ActionAckMessage {
    type: 'ACTION_ACK';
    actionId: string;
    status: 'success' | 'error';
    error?: string;
    data?: any;
}

/**
 * Service Interfaces (Contracts)
 * Note: These are evolving and will be fully defined in Phase 4 (Dependency Injection).
 */

export interface IWebSocketService {
    connect(): void;
    disconnect(): void;
    login(username: string, password: string): AsyncResult<LoginResult>;
    setCallbacks(callbacks: WebSocketCallbacks): void;
    clearCallbacks(): void;
}

export interface IDatabaseService {
    init(): Promise<void>;
    saveRelease(release: Release): Promise<void>;
    saveReleasesBatch(releases: Release[]): Promise<void>;
    getReleases(userId: string, limit?: number, offset?: number, searchQuery?: string): Promise<Release[]>;
    updateReleaseTracks(userId: string, releaseId: number, tracksJson: string): Promise<void>;
    clearUserCollection(userId: string): Promise<void>;
    clearAll(): Promise<void>;
    _resetForTesting(): void; // Added for completeness from previous work
}

export interface ICollectionSyncService {
    syncCollection(userId: string, callbacks?: SyncCallbacks): AsyncResult<SyncResult>;
    isSyncing(): boolean;
}

export interface IAuthService {
    login(username: string, password: string): Promise<void>;
    logout(): void;
    isAuthenticated(): boolean;
}
